"""
Goal filter for geometry problems.

Provides filtering logic to select valid and meaningful goals
from generated geometric constructions.
"""

import logging
import re

from newclid.statement import Statement


class GoalFilter:
    """
    Filter for selecting valid geometry goals.

    Filters out trivial, redundant, or invalid goals from the set of
    possible goals generated by the solver.
    """

    def naive_goal_filter(self, goal_name: str, goal_args: list, dep_graph) -> bool:
        """
        Apply basic filtering rules for a goal.

        Args:
            goal_name: Name of the goal predicate.
            goal_args: Arguments of the goal.
            dep_graph: Dependency graph for checking statements.

        Returns:
            True if the goal passes the filter, False otherwise.
        """
        if goal_name == "cong":
            return self._naive_cong_filter(goal_args, dep_graph)
        elif goal_name == "para":
            return self._naive_para_filter(goal_args, dep_graph)
        elif goal_name == "coll":
            return True
        elif goal_name == "perp":
            return True
        elif goal_name == "cyclic":
            return True
        elif goal_name == "eqratio":
            return self._naive_eqratio_filter(goal_args, dep_graph)
        elif goal_name == "eqangle":
            return self._naive_eqangle_filter(goal_args, dep_graph)
        elif goal_name == "acompute":
            return True
        elif goal_name == "aconst":
            return self._naive_aconst_filter(goal_args, dep_graph)
        elif goal_name == "rcompute":
            return True
        elif goal_name == "rconst":
            return self._naive_rconst_filter(goal_args, dep_graph)
        elif goal_name == "simtri" or goal_name == "simtrir":
            return self._naive_simtri_filter(goal_args, dep_graph)
        elif goal_name == "contri" or goal_name == "contrir":
            return self._naive_contri_filter(goal_args, dep_graph)
        return False

    def _naive_cong_filter(self, args: list, dep_graph) -> bool:
        """Filter: reject cong AB = AB (same segment)."""
        seg1 = {args[0], args[1]}
        seg2 = {args[2], args[3]}
        if seg1 == seg2:
            return False
        return True

    def _naive_para_filter(self, args: list, dep_graph) -> bool:
        """Filter: reject para AB || AC (implies collinearity)."""
        if len(set(args)) < 4:
            return False
        return True

    def _naive_simtri_filter(self, args: list, dep_graph) -> bool:
        """Filter: reject simtri ABC ~ ABC (same triangle) or if contri holds."""
        tri_1 = {args[0], args[1], args[2]}
        tri_2 = {args[3], args[4], args[5]}
        if tri_1 == tri_2:
            return False
        sm = Statement.from_tokens(["contri"] + args, dep_graph)
        if sm.check():
            return False
        sm = Statement.from_tokens(["contrir"] + args, dep_graph)
        if sm.check():
            return False
        return True

    def _naive_contri_filter(self, args: list, dep_graph) -> bool:
        """Filter: reject contri ABC = ABC (same triangle)."""
        tri_1 = {args[0], args[1], args[2]}
        tri_2 = {args[3], args[4], args[5]}
        if tri_1 == tri_2:
            return False
        return True

    def _naive_eqangle_filter(self, args: list, dep_graph) -> bool:
        """Filter eqangle goals for trivial or reducible cases."""
        seg_1 = {args[0], args[1]}
        seg_2 = {args[2], args[3]}
        seg_3 = {args[4], args[5]}
        seg_4 = {args[6], args[7]}

        a1_args = list(set(args[:4]))
        a2_args = list(set(args[4:]))
        if not (len(a1_args) == 3 and len(a2_args)) == 3:
            return False

        # Reject: eqangle (AB,AB) = (CD,EF) => para CD||EF
        if seg_1 == seg_2 or seg_3 == seg_4:
            return False

        # Reject: eqangle (AB,CD) = (AB,CD)
        if seg_1 == seg_3 and seg_2 == seg_4:
            return False

        # Reject: eqangle (AB,CD) = (CD,AB) => perp AB CD
        if seg_1 == seg_4 and seg_2 == seg_3:
            return False

        # Reject if any pair has computable angle or is parallel/perpendicular
        parallel_sets = [
            [args[0], args[1], args[2], args[3]],
            [args[0], args[1], args[4], args[5]],
            [args[0], args[1], args[6], args[7]],
            [args[2], args[3], args[4], args[5]],
            [args[2], args[3], args[6], args[7]],
            [args[4], args[5], args[6], args[7]],
        ]
        for arg_set in parallel_sets:
            sm = Statement.from_tokens(["acompute"] + arg_set, dep_graph)
            if sm and sm.check():
                return False
        for arg_set in parallel_sets:
            sm = Statement.from_tokens(["para"] + arg_set, dep_graph)
            if sm.check():
                return False
        for arg_set in parallel_sets:
            sm = Statement.from_tokens(["perp"] + arg_set, dep_graph)
            if sm.check():
                return False

        return True

    def _naive_eqratio_filter(self, args: list, dep_graph) -> bool:
        """Filter eqratio goals for trivial or reducible cases."""
        seg_1 = {args[0], args[1]}
        seg_2 = {args[2], args[3]}
        seg_3 = {args[4], args[5]}
        seg_4 = {args[6], args[7]}

        # Reject: eqratio AB/AB = CD/EF => cong CD = EF
        if seg_1 == seg_2 or seg_3 == seg_4:
            return False

        # Reject: eqratio AB/CD = AB/CD or AB/CD = AB/EF => cong CD = EF
        if seg_1 == seg_3 or seg_2 == seg_4:
            return False

        # Reject: eqratio AB/CD = CD/AB => cong AB = CD
        if seg_1 == seg_4 and seg_3 == seg_4:
            return False

        # Reject if any pair has same length
        sets = [
            [args[0], args[1], args[2], args[3]],
            [args[0], args[1], args[4], args[5]],
            [args[2], args[3], args[6], args[7]],
            [args[4], args[5], args[6], args[7]],
        ]
        for arg_set in sets:
            sm = Statement.from_tokens(["cong"] + arg_set, dep_graph)
            if sm.check():
                return False
            for ratio in ("1/1",):
                sm = Statement.from_tokens(["rconst"] + arg_set + [ratio], dep_graph)
                if sm.check():
                    return False
            sm = Statement.from_tokens(["rcompute"] + arg_set, dep_graph)
            if sm.check():
                return False

        return True

    def _naive_rconst_filter(self, args: list, dep_graph) -> bool:
        """Filter: reject rconst with ratio 1/1."""
        if args[-1] == "1/1":
            return False
        return True

    def _naive_aconst_filter(self, args: list, dep_graph) -> bool:
        """Filter: reject aconst with common angles."""
        if args[-1] in ("0pi/1", "1pi/2", "1pi/1", "1pi/3", "2pi/3", "1pi/4", "3pi/4"):
            return False
        return True

    def goal_filter(self, possible_goals: list, dep_graph) -> list:
        """
        Filter a list of possible goals.

        Args:
            possible_goals: List of goal statements to filter.
            dep_graph: Dependency graph for checking statements.

        Returns:
            Filtered list of valid goals.
        """

        def group_equivalent_predicates(goals, predicate_type):
            """Group equivalent predicate goals together."""
            predicate_groups = []
            goal_groups = []

            for goal in goals:
                args = [arg.name for arg in goal.args]
                found_group = False

                for i, (group, goal_group) in enumerate(
                    zip(predicate_groups, goal_groups)
                ):
                    for existing_pair in group:
                        sm1 = Statement.from_tokens(
                            [predicate_type] + args[:4] + existing_pair, dep_graph
                        )
                        sm2 = Statement.from_tokens(
                            [predicate_type] + args[4:] + existing_pair, dep_graph
                        )
                        if sm1.check() or sm2.check():
                            found_group = True
                            if args[:4] not in group:
                                group.append(args[:4])
                            if args[4:] not in group:
                                group.append(args[4:])
                            goal_group.append(goal)
                            break
                    if found_group:
                        break

                if not found_group:
                    predicate_groups.append([args[:4], args[4:]])
                    goal_groups.append([goal])

            return goal_groups

        def check_equivalence(p1, p2, token_type):
            args1 = [arg.name for arg in p1.args]
            args2 = [arg.name for arg in p2.args]
            statements = [
                Statement.from_tokens(
                    [token_type, args1[i], args1[i + 1], args2[i], args2[i + 1]],
                    dep_graph,
                )
                for i in range(0, len(args1), 2)
            ]
            return all(sm.check() for sm in statements)

        def remove_duplicates(goals, equivalence_fn, token_type):
            unique_goals = []
            for goal in goals:
                if not any(
                    equivalence_fn(existing_goal, goal, token_type)
                    for existing_goal in unique_goals
                ):
                    unique_goals.append(goal)
            return unique_goals

        # First pass: apply naive filters and collect eqpoint pairs
        filtered_goals = []
        eq_pairs = set()
        for goal in possible_goals:
            parts = goal.to_str().split(" ")
            if parts[0] == "eqpoint":
                eq_pairs.add(frozenset([parts[1], parts[2]]))
            if self.naive_goal_filter(parts[0], parts[1:], dep_graph):
                filtered_goals.append(goal)
        possible_goals = filtered_goals

        # Second pass: remove goals with equivalent points
        filtered_goals = []
        for goal in possible_goals:
            parts = goal.to_str().split(" ")
            args = parts[1:]
            discard = False
            for i in range(len(args)):
                for j in range(i + 1, len(args)):
                    if frozenset([args[i], args[j]]) in eq_pairs:
                        discard = True
                        break
                if discard:
                    break
            if not discard:
                filtered_goals.append(goal)
        possible_goals = filtered_goals

        # Separate goals by type
        eqangle_goals = [
            goal for goal in possible_goals if goal.predicate.NAME == "eqangle"
        ]

        eqratio_goals = [
            goal for goal in possible_goals if goal.predicate.NAME == "eqratio"
        ]

        other_goals = [
            goal
            for goal in possible_goals
            if goal.predicate.NAME
            not in (
                "eqangle",
                "eqratio",
                "eqratio3",
                "ncoll",
                "midp",
                "acompute",
                "rcompute",
                "sameside",
                "sameclock",
            )
        ]

        return eqangle_goals + eqratio_goals + other_goals

    def aux_predicates_valid_check(self, llm_output: str) -> bool:
        """
        Check if auxiliary predicates in LLM output are valid.

        Args:
            llm_output: LLM output string containing auxiliary predicates.

        Returns:
            True if all auxiliary predicates are valid.
        """

        def is_valid(statement: str, valid_predicates: set) -> bool:
            prefix_match = re.match(r"(x00 \w+)\s*:\s*(.*)", statement)
            if prefix_match:
                rest = prefix_match.group(2)
                segments = re.split(r"\s*\[\d+\]", rest)
                segments = [seg.strip() for seg in segments if seg.strip()]
                for segment in segments:
                    parts = segment.split()
                    if parts and parts[0] not in valid_predicates:
                        logging.debug(f"Invalid auxiliary predicate: {parts[0]}")
                        return False
            return True

        valid_aux_predicates = {
            "perp",
            "para",
            "cong",
            "coll",
            "eqangle",
            "cyclic",
            "midp",
        }
        aux_match = re.match(r"<aux>\s*(.*)\s*</aux>", llm_output)

        if aux_match:
            aux_content = aux_match.group(1)
            for content_item in aux_content.split(";"):
                content_item = content_item.strip()
                if content_item:
                    if not is_valid(content_item, valid_aux_predicates):
                        return False
        return True
