from enum import Enum


class Predicate(Enum):
    COLLINEAR = "coll"
    COLLINEAR_X = "collx"
    PARALLEL = "para"
    PERPENDICULAR = "perp"
    MIDPOINT = "midp"
    CONGRUENT = "cong"
    CONGRUENT_2 = "cong2"
    CIRCLE = "circle"
    CYCLIC = "cyclic"
    EQANGLE = "eqangle"
    EQANGLE6 = "eqangle6"
    EQRATIO = "eqratio"
    EQRATIO6 = "eqratio6"
    EQRATIO3 = "eqratio3"
    EQRATIO4 = "eqratio4"
    SIMILAR_TRIANGLE = "simtri"
    SIMILAR_TRIANGLE_REFLECTED = "simtri2"
    SIMILAR_TRIANGLE_BOTH = "simtri*"
    CONTRI_TRIANGLE = "contri"
    CONTRI_TRIANGLE_REFLECTED = "contri2"
    CONTRI_TRIANGLE_BOTH = "contri*"
    CONSTANT_ANGLE = "aconst"
    CONSTANT_RATIO = "rconst"
    COMPUTE_ANGLE = "acompute"
    COMPUTE_RATIO = "rcompute"
    S_ANGLE = "s_angle"
    # Numericals
    SAMESIDE = "sameside"
    DIFFERENT = "diff"
    NON_COLLINEAR = "ncoll"
    NON_PARALLEL = "npara"
    NON_PERPENDICULAR = "nperp"
    # Fix_x ? What is that ?
    FIX_L = "fixl"
    FIX_C = "fixc"
    FIX_B = "fixb"
    FIX_T = "fixt"
    FIX_P = "fixp"
    # What is that also ?
    IND = "ind"
    INCI = "inci"
